sudo: required
services:
  - docker

before_install:
  - docker build -t nikhilgb/test-docker-push

script:
  - docker run nikhilgb/react-test npm test -- --coverage

after_success:
  - docker build -t nikhilgb/multi-client ./client
  - docker build -t nikhilgb/multi-nginx ./nginx
  - docker build -t nikhilgb/multi-server ./server
  - docker build -t nikhilgb/multi-worker ./worker
  - echo "$docker_password" | docker login -u "docker_id" --password-stdin
  - docker push nikhilgb/multi-client:latest
  - docker push nikhilgb/multi-nginx:latest
  - docker push nikhilgb/multi-server:latest
  - docker push nikhilgb/multi-worker:latest

